## Experiment No.1

## Develop a python program to read n digit integer number and display each digit.

In [8]:
n=int(input("Enter the digit:"))
if n>0:
    number=int(input(f"Enter a {n}-digit integer"))
    if number>=10**(n-1)and number<10**n:
        for i in range(n):
            digit=number//(10**(n-1))
            print(digit) 
            number %=10**(n-1)
            n-=1
    else:
        print(f"Please enter a{n}-digit integer")
else:
    print("Please enter a valid number of digits(greater than zero)")

Enter the digit:3
Enter a 3-digit integer123
1
2
3


## 2.Develop the python program to accept 4 numbers and display them in sorted order using a minimum numbers of if else statements.

In [7]:
a=int(input("Enter the first number:"))
b=int(input("Enter the second number:"))
c=int(input("Enter the third number:"))
d=int(input("Enter the fourth number:"))
if a>b:a,b=b,a
if c>d:c,d=d,c
if a>c:a,c=c,a
if b>d:b,d=d,b
if b>c:b,c=c,b
print("The sorted numbers are:",a,b,c,d)


Enter the first number:10
Enter the second number:5
Enter the third number:7
Enter the fourth number:8
The sorted numbers are: 5 7 8 10


## 4.Develop a program for checking if a given n digit number is Palindrome or not.

In [5]:
number=int(input("Enter an n-digit number:"))
original_number=number
reversed_number=0
while number>0:
    digit=number%10
    reversed_number=reversed_number*10+digit
    number//=10
if original_number==reversed_number:
    print("Palindrome")
else:
    print("Not a Palindrome")

Enter an n-digit number:135431
Not a Palindrome


## 5.Develop a python script to display a multiplication table for given integer n.

In [11]:
n=int(input("Enter an integer for the multiplication table:"))
print(f"Multiplication table for{n}:")
for i in range(1,11):
    result=n*i
    print(f"{n}X{i}={result}")

Enter an integer for the multiplication table:5
Multiplication table for5:
5X1=5
5X2=10
5X3=15
5X4=20
5X5=25
5X6=30
5X7=35
5X8=40
5X9=45
5X10=50


## 3.Develop a python script to mean,median,mode,variance and Standard deviation of n integer number

In [7]:
n=int(input("Enter the number of elements:"))
numbers=[int(input(f"Enter number{i+1}:"))for i in range(n)]
mean=sum(numbers)/n
numbers.sort()
if n%2==0:
    median=(numbers[n//2-1]+numbers[n//2])/2
else:
    median=numbers[n//2]
frequency={num:numbers.count(num)for num in numbers}
max_count=max(frequency.values())
mode=[k for k,V in frequency.items() if V==max_count]
if len(mode)==n:
    mode="No mode"
mean_difference_squared_sum=sum((x-mean)**2 for x in numbers)
variance_sample=mean_difference_squared_sum/(n-1)if n>1 else 0
variance_population=mean_difference_squared_sum/n
std_deviation_sample=variance_sample**0.5
std_deviation_population=variance_population**0.5
print(f"Mean:{mean}")
print(f"Median:{median}")
print(f"Mode:{mode}")
print(f"Sample variance:{variance_sample}")
print(f"Population variance:{variance_population}")
print(f"Sample standard deviation:{std_deviation_sample}")
print(f"Population standard deviation:{std_deviation_population}")

Enter the number of elements:6
Enter number1:3
Enter number2:4
Enter number3:5
Enter number4:6
Enter number5:8
Enter number6:9
Mean:5.833333333333333
Median:5.5
Mode:No mode
Sample variance:5.366666666666667
Population variance:4.472222222222222
Sample standard deviation:2.316606713852541
Population standard deviation:2.1147629234082532


## 6.Develop a python script to rotate right about a given position in that list and display them.

In [1]:
number=int(input("Enter the integer number"))
revs_number=0
while(number>0):
    remainder=number%10
    revs_number=(revs_number*10)+remainder
    number=number//10
print("The reverse number is:{}".format(revs_number))

Enter the integer number253
The reverse number is:352


## 7.Develop a python script to interchange the digits of given integer number.

In [1]:
def interchange_digits(number,pos1,pos2):
    number_str=str(number)
    number_list=list(number_str)
    number_list[pos1-1],number_list[pos2-1]=number_list[pos2-1],number_list[pos1-1]
    interchanged_number=int(''.join(number_list))
    return interchanged_number
number=int(input('Enter the user input:'))
pos1=int(input('Enter the 1st position which you want to swap:'))
pos2=int(input('Enter the 2nd position which you want to swap:'))
interchanged_number=interchange_digits(number,pos1,pos2)
print("Original number:",number)
print("Interchanged number:",interchanged_number)

                            

Enter the user input:253
Enter the 1st position which you want to swap:1
Enter the 2nd position which you want to swap:3
Original number: 253
Interchanged number: 352


## 8.Develop a python program to capitalize a given list of strings.

In [14]:
def capitalize_strings(string_list):
    return[s.capitalize()for s in string_list]
input_strings=['hello','good','how','simple']
capitalized_strings=capitalize_strings(input_strings)
print(capitalized_strings)

['Hello', 'Good', 'How', 'Simple']


## 9.Using a dictionary develop a python program to determine amd print the number of duplicate words in the sentence

In [1]:
def count_duplicate_words(sentence):
    words=sentence.split()
    word_count={}
    for word in words:
        word=word.lower()
        if word in word_count:
            word_count[word]+=1
        else:
            word_count[word]=1
    duplicates={word:count for word,count in word_count.items()if count>1}
    if duplicates:
        print("Duplicate words and their counts:")
        for word,count in duplicates.items():
            print(f"{word}:{count}")
    else:
        print("No duplicate words found")
sentence=input('Enter a sentence:')
count_duplicate_words(sentence)

Enter a sentence:struggle struggles the struggle don't struggle the struggle if you struggle the struggle struggle struggles you
Duplicate words and their counts:
struggle:7
struggles:2
the:3
you:2


## 10 Develop a python program to read numpy array and print row(sum,mean,std)and column(sum,mean,std).

In [1]:
from numpy import asarray
data=[[1,2,3],[4,5,6]]
data=asarray(data)
print("Numpy array")
print(data)
print("---------------")
totalr=data.sum(axis=1)
totalc=data.sum(axis=0)
print("Row sum")
print(totalr)
print("Column sum")
print(totalc)
print("---------------")
meanr=data.mean(axis=1)
meanc=data.mean(axis=0)
print("Row mean")
print(meanr)
print("Column mean")
print(meanc)
print("---------------")
stdr=data.std(axis=1)
stdc=data.std(axis=0)
print("Row STD")
print(stdr)
print("column STD")
print(stdc)


Numpy array
[[1 2 3]
 [4 5 6]]
---------------
Row sum
[ 6 15]
Column sum
[5 7 9]
---------------
Row mean
[2. 5.]
Column mean
[2.5 3.5 4.5]
---------------
Row STD
[0.81649658 0.81649658]
column STD
[1.5 1.5 1.5]


## 11.Develop a python program to read and print in the console CSV file.

In [6]:
import csv
file=open('employeee.csv',mode='r')
csv_reader=csv.reader(file,delimiter=',')
line_count=0
for row in csv_reader:
    if line_count==0:
        print(f'Column names are {",".join(row)}')
        line_count+=1
    else:
        print(f'\t{row[0]} works in the {row[1]} department,and was born in {row[2]}.')
        line_count+=1
print(f'Processed {line_count} lines.')
file.close()

Column names are name,department,birthday_month
	smith works in the accounting department,and was born in november.
	erica works in the IT department,and was born in march.
	john works in the HR department,and was born in april.
Processed 4 lines.


## 12.Develop a python program to read a HTML file with a basic tags and construct a dictionary and display the same in the console.

In [12]:
import pandas as pd
def read_html_to_dict(html_file):
    tables=pd.read_html(html_file)
    tables_dict={}
    for i,table in enumerate(tables):
        table_dict=table.to_dict(orient='list')
        tables_dict[f'Table_{i+1}']=table_dict
    return tables_dict
if __name__=='__main__':
    html_file='student.html'
    result=read_html_to_dict(html_file)
    print(result)

{'Table_1': {'Name': ['Mahima', 'Srijanya'], 'Age': [18, 18]}, 'Table_2': {'Country': ['India', 'America'], 'Capital': ['Delhi', 'Washington']}}
